dist: trusty
sudo: required
language:
  - cpp
compiler:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libssl-dev
      - libsqlite3-dev
      - libmicrohttpd-dev
      - gettext
      - libicu-dev
      - icu-devtools
      - libicu52
      - autoconf
      - automake
      - openssl
      - libtool
script:
  - sudo pip install --upgrade pip
  - sudo pip install codecov
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - ./configure
  - make
after_success:
  - codecov
