language: cpp
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=g++-7 CC=gcc-7 && CXX=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libssl-dev
            - libsqlite3-dev
            - libmicrohttpd-dev
            - gettext
            - libicu-dev
            - icu-devtools
            - autoconf
            - automake
            - openssl
            - libtool
