dist: bionic
sudo: required
language:
  - cpp
compiler:
  - g++
before_install:
  - sudo add-apt-repository ppa:qpid/released
  - sudo add-apt-repository ubuntu-toolchain-r/test
  - sudo apt update
addons:
  apt:
    packages:
      - g++-7
      - libssl-dev
      - libsqlite3-dev
      - gettext
      - libicu-dev
      - icu-devtools
      - autoconf
      - automake
      - openssl
      - libtool
      - libmaxminddb-dev
      - libmariadb-dev
      - libqpid-proton-cpp12-dev
script:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - sudo ln -s /usr/include/mysql /usr/include/mariadb
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - ./configure
  - make
