dist: xenial
sudo: required
language:
  - cpp
compiler:
  - c++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libssl-dev
      - libsqlite3-dev
      - libmicrohttpd-dev
      - gettext
      - libicu-dev
      - icu-devtools
      - autoconf
      - automake
      - openssl
      - libtool
      - libmaxminddb-dev
      - libmysqlclient-dev
script:
  - sudo ln -s /usr/bin/c++-8 /usr/local/bin/c++
  - export CXX=/usr/local/bin/c++
  - ./configure
  - make
