dist: bionic
sudo: required
language:
  - cpp
compiler:
  - c++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - c++
      - gcc
      - libssl-dev
      - libsqlite3-dev
      - libmicrohttpd-dev
      - gettext
      - libicu-dev
      - icu-devtools
      - autoconf
      - automake
      - openssl
      - libtool
      - libmaxminddb-dev
      - libmysqlclient-dev
script:
  - ./configure
  - make
