dist: trusty
sudo: required
language:
  - cpp
compiler:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libssl-dev
      - libsqlite3-dev
      - libmicrohttpd-dev
      - gettext
      - libicu-dev
      - icu-devtools
      - libicu52
      - autoconf
      - automake
      - openssl
      - libtool
      - libcurl4-gnutls-dev
      - lcov
script:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - export CODECOV_TOKEN=015df856-84d9-4d28-a9a1-d81b1c88d213
  - ./configure
  - make

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory ./src --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
