dist: bionic
sudo: required
language:
  - cpp
compiler:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-7
      - libssl-dev
      - libsqlite3-dev
      - gettext
      - libicu-dev
      - icu-devtools
      - autoconf
      - automake
      - openssl
      - libtool
      - libmaxminddb-dev
      - libmariadb-dev
script:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - git clone https://github.com/apache/qpid-proton.git
  - cd qpid-proton
  - mkdir build && cd build && cmake .. && make all && make test && make install
  - ./configure
  - make
