dist: bionic
sudo: required
language:
  - cpp
compiler:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-9
      - libssl-dev
      - libsqlite3-dev
      - gettext
      - libicu-dev
      - icu-devtools
      - autoconf
      - automake
      - openssl
      - libtool
      - libmaxminddb-dev
      - libmysqlclient-dev
      - libqpid-proton-cpp8-dev
script:
  - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
  - sudo ln -s /usr/include/mysql /usr/include/mariadb
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  - ./configure
  - make
