dist: buster
sudo: required
language:
  - cpp
compiler:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libssl-dev
      - libsqlite3-dev
      - libmicrohttpd-dev
      - gettext
      - libicu-dev
      - icu-devtools
      - libicu52
      - autoconf
      - automake
      - openssl
      - libtool
      - libmaxminddb-dev
script:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - export CODECOV_TOKEN=015df856-84d9-4d28-a9a1-d81b1c88d213
  - ./configure
  - make
