language: cpp
before_install:
  - sudo apt-get install -y nano gcc cpp g++ libssl-dev libsqlite3-dev git make sudo libmicrohttpd-dev gettext libicu-dev autoconf automake openssl libtool
matrix:
  include:
    os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
