name: C/C++ CI

on: [push]

jobs:
  build:trusty:
    runs-on: trusty:base
    
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: sudo apt-get install g++ libssl-dev libsqlite3-dev make gettext libicu-dev openssl libmaxminddb0 libmaxminddb-dev mmdb-bin libmariadb-dev libqpid-proton-cpp11-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
