
name: macOS
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip macos ci]')"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: brew install qpid-proton && find /usr/local/Cellar/qpid-proton/0.38.0 -name 'container.hpp'
